---
engines:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
  duplication:
    enabled: false
    checks:
      Identical code:
        enabled: false
    config:
      languages:
        python:
          mass_threshold: 190
  eslint:
    enabled: true
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  radon:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- configs/**/*
- var/**/*
- password_manager_server/restapi/tests/**/*
- password_manager_server/restapi/migrations/**/*
- password_manager_server/static/**/*