version: '2'

services:
  postgres:
    image: postgres
    networks:
      - password-manager-server-network-test

  password-server-image-test:
    build: .
    depends_on:
      - postgres
    links:
     - postgres
    environment:
     - PSONO_EMAIL_HOST=172.17.0.1
     - PSONO_EMAIL_FROM=test@example.com
     - PSONO_ACTIVATION_LINK_SECRET=9SruC2qPmKScVzGaF4378LW4rvNNkK2G3Gddqy9kPQqgkjeDQjs7jaLBCstgtJTt
     - PSONO_SECRET_KEY=RQTKawYQv4w6KkuphcLzLu7r5ap7xE5DSDu5SkKXjMnWBQ93mcMKjdZfeZkY2Y7C
    networks:
      - password-manager-server-network-test

networks:
  password-manager-server-network-test:
    driver: bridge